### ISSUE TITLE
have you tried updating meteor and all the packages to their most current versions?

### ISSUE THREAD

**Issue by sergical** [mrphu3074/react-material-ui-ssr-examples#1]
I am trying to use your setup for SSR but in `mui.init.jsx` i am getting the following server error `TypeError: object is not a function
W20151211-12:11:47.163(-5)? (STDERR)     at both/0.init/mui.init.jsx:2:16`

**Comment by mrphu3074** [comment]
i'm sorry @416serg, this repo using very old MUI version.  
Please use latest version and consider this lines to support SSR

``` js
// Defer Script Loading
FlowRouter.setDeferScriptLoading(true);

var timeInMillis = 1000 * 10; // 10 secs
FlowRouter.setPageCacheTimeout(timeInMillis);
```

**Comment by sergical** [comment]
@mrphu3074 hey Phu, thanks for the comment, however I am not sure if you're aware of the server side error that comes up. `Material-UI expects the global navigator.userAgent to be defined for server-side rendering. Set this property when receiving the request headers.`

**Comment by mrphu3074** [comment]
@416serg this is an error from inline style css, i have no solution to fix it completely. That error come from server side, so you can init a fake user agent like:

```
global.navigator = { userAgent: 'mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36' };
```

**Comment by sergical** [comment]
cheers, that could work for now, I'll deal with production env later.
